Add Gitalk comment
CaiJimmy/hugo-theme-stack pull request #351
Opened 2021-09-12 14:18 UTC by Cookiekira

https://github.com/gitalk/gitalk
Gitalk is a modern comment component based on GitHub Issue and Preact.
<img width="1257" alt="截屏2021-09-12 下午10 18 02" src="https://user-images.githubusercontent.com/42908926/132991146-1f3a8c3b-a436-4f1c-a01c-2f03230cffb3.png">

2021-09-13 03:35 UTC, Cookiekira commented
Delete .DS_Store file

2021-09-15 21:37 UTC, CJ-Jackson commented
@Cookiekira This might come in handy for you. 😉 https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/

2021-09-17 20:12 UTC, CaiJimmy requested changes
Thanks for the PR 💖

2021-09-17 20:12 UTC, CaiJimmy commented on layouts/partials/comments/provider/gitalk.html
> +<script src="https://cdn.bootcdn.net/ajax/libs/blueimp-md5/2.18.0/js/md5.js"></script>
Since the most of third-party resources of this theme are fetched from JSDelivr, I think it's better to switch to JSDelivr.

2021-09-17 20:12 UTC, CaiJimmy commented on layouts/partials/comments/provider/gitalk.html
> +
Remove this blank line

2021-09-17 20:12 UTC, CaiJimmy commented on layouts/partials/comments/provider/gitalk.html
> +  })();
Please use 4 space indentations

2021-09-18 00:51 UTC, Cookiekira reviewed
switch to jsDelivr and 4 tab width

2021-09-18 00:52 UTC, Cookiekira reviewed
switch to jsDelivr and 4 tab width

2021-09-18 08:01 UTC, CaiJimmy approved these changes

2021-09-18 08:03 UTC, merged

2021-09-18 08:03 UTC, CaiJimmy commented
Thanks 👍