Added translations for tag and category widgets
CaiJimmy/hugo-theme-stack pull request #997
Opened 2024-03-30 04:22 UTC by BaDos

Hi!

Please merge this PR.
I have aded translations for tag and category widgets.

Thanks 😉

2024-03-30 22:01 UTC, CaiJimmy requested changes
Thanks for the PR!

2024-03-30 22:01 UTC, CaiJimmy commented on .gitignore
Could you exclude this change from the pull request please?

2024-03-31 23:32 UTC, BaDos commented on .gitignore
Removed

2024-04-02 18:45 UTC, CaiJimmy commented on .gitignore
Thanks!

2024-04-02 18:46 UTC, merged